"""initial PostgreSQL schema

Revision ID: eb4b123ae501
Revises: 
Create Date: 2026-08-17 14:42:54.448308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb4b123ae501'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_type IN ('bookmaker', 'history', 'manual')", name=op.f('ck_sources_source_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_sources_code'))
    )
    op.create_table('teams',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_normalized_name'), 'teams', ['normalized_name'], unique=True)
    op.create_table('normalization_reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("entity_type IN ('player', 'team', 'tournament')", name=op.f('ck_normalization_reviews_entity_type')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_normalization_reviews_status')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_normalization_reviews_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalization_reviews'))
    )
    op.create_index('ix_normalization_reviews_status', 'normalization_reviews', ['status'], unique=False)
    op.create_table('player_aliases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_aliases_player_id_players')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_player_aliases_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_aliases')),
    sa.UniqueConstraint('source_id', 'normalized_alias', name='uq_player_alias_source_norm')
    )
    op.create_index('ix_player_aliases_alias', 'player_aliases', ['alias'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_payloads_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payloads'))
    )
    op.create_index('ix_raw_payloads_content_sha256', 'raw_payloads', ['content_sha256'], unique=False)
    op.create_index('ix_raw_payloads_received_at', 'raw_payloads', ['received_at'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_team_aliases_source_id_sources')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases')),
    sa.UniqueConstraint('source_id', 'normalized_alias', name='uq_team_alias_source_norm')
    )
    op.create_index('ix_team_aliases_alias', 'team_aliases', ['alias'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('game', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_tournaments_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_tournament_source_external')
    )
    op.create_index('ix_tournaments_normalized_name', 'tournaments', ['normalized_name'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('game', sa.String(length=64), nullable=True),
    sa.Column('tournament_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('player1_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('player2_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('team1_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('team2_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'finished', 'cancelled', 'unknown')", name=op.f('ck_events_status')),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name=op.f('fk_events_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_events_player2_id_players')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], name=op.f('fk_events_raw_payload_id_raw_payloads')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_events_source_id_sources')),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], name=op.f('fk_events_team1_id_teams')),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], name=op.f('fk_events_team2_id_teams')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_events_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_event_source_external')
    )
    op.create_index('ix_events_external_id', 'events', ['external_id'], unique=False)
    op.create_index('ix_events_source_id', 'events', ['source_id'], unique=False)
    op.create_index('ix_events_started_at', 'events', ['started_at'], unique=False)
    op.create_table('parser_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parser_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('events_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('events_parsed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('events_rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_payload_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'error')", name=op.f('ck_parser_runs_status')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], name=op.f('fk_parser_runs_raw_payload_id_raw_payloads')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_parser_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parser_runs'))
    )
    op.create_index('ix_parser_runs_source_started', 'parser_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('event_matches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bookmaker_event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('matched', 'ambiguous', 'rejected')", name=op.f('ck_event_matches_status')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_event_matches_confidence')),
    sa.ForeignKeyConstraint(['bookmaker_event_id'], ['events.id'], name=op.f('fk_event_matches_bookmaker_event_id_events')),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], name=op.f('fk_event_matches_source_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_matches')),
    sa.UniqueConstraint('source_event_id', 'bookmaker_event_id', name='uq_event_match_pair')
    )
    op.create_index('ix_event_matches_status', 'event_matches', ['status'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('side IN (1, 2)', name=op.f('ck_event_participants_side')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_participants_event_id_events')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_event_participants_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_event_participants_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_participants')),
    sa.UniqueConstraint('event_id', 'side', name='uq_event_participant_side')
    )
    op.create_table('markets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_markets_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('event_id', 'external_id', name='uq_market_event_external')
    )
    op.create_index('ix_markets_event_id', 'markets', ['event_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=2), nullable=False),
    sa.Column('is_draw', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.CheckConstraint("winner IN ('P1', 'X', 'P2')", name=op.f('ck_results_winner')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_results_event_id_events')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], name=op.f('fk_results_raw_payload_id_raw_payloads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    op.create_index('ix_results_event_id', 'results', ['event_id'], unique=True)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bookmaker_source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('market_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('odds', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.CheckConstraint('odds > 1', name=op.f('ck_odds_snapshots_odds_positive')),
    sa.ForeignKeyConstraint(['bookmaker_source_id'], ['sources.id'], name=op.f('fk_odds_snapshots_bookmaker_source_id_sources')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_odds_snapshots_event_id_events')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_odds_snapshots_market_id_markets')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], name=op.f('fk_odds_snapshots_raw_payload_id_raw_payloads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    op.create_index('ix_odds_event_market_received', 'odds_snapshots', ['event_id', 'market_id', 'received_at'], unique=False)
    op.create_index('ix_odds_snapshots_event_id', 'odds_snapshots', ['event_id'], unique=False)
    op.create_index('ix_odds_snapshots_received_at', 'odds_snapshots', ['received_at'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('odds_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('market_code', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('fair_odds', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('value_ratio', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('value_percent', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('display_odds', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('anomaly_flags', sa.JSON(), nullable=False),
    sa.Column('feature_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability > 0 AND probability <= 1', name=op.f('ck_model_predictions_probability')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_model_predictions_event_id_events')),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], name=op.f('fk_model_predictions_odds_snapshot_id_odds_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index('ix_model_predictions_created_at', 'model_predictions', ['created_at'], unique=False)
    op.create_index('ix_model_predictions_event_id', 'model_predictions', ['event_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=False),
    sa.Column('minimum_odds', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('safety_multiplier', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('stake_mode', sa.String(length=32), nullable=True),
    sa.Column('suggested_stake', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bet_multiplier', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('filter_reasons', sa.JSON(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decision IN ('alert', 'skip')", name=op.f('ck_signals_decision')),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], name=op.f('fk_signals_prediction_id_model_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('prediction_id', name=op.f('uq_signals_prediction_id'))
    )
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('stake', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payout', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('win', 'loss', 'return', 'void')", name=op.f('ck_settlements_outcome')),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_settlements_result_id_results')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_settlements_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index('ix_settlements_signal_id', 'settlements', ['signal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settlements_signal_id', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_model_predictions_event_id', table_name='model_predictions')
    op.drop_index('ix_model_predictions_created_at', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('ix_odds_snapshots_received_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_event_id', table_name='odds_snapshots')
    op.drop_index('ix_odds_event_market_received', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_results_event_id', table_name='results')
    op.drop_table('results')
    op.drop_index('ix_markets_event_id', table_name='markets')
    op.drop_table('markets')
    op.drop_table('event_participants')
    op.drop_index('ix_event_matches_status', table_name='event_matches')
    op.drop_table('event_matches')
    op.drop_index('ix_parser_runs_source_started', table_name='parser_runs')
    op.drop_table('parser_runs')
    op.drop_index('ix_events_started_at', table_name='events')
    op.drop_index('ix_events_source_id', table_name='events')
    op.drop_index('ix_events_external_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_tournaments_normalized_name', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index('ix_team_aliases_alias', table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index('ix_raw_payloads_received_at', table_name='raw_payloads')
    op.drop_index('ix_raw_payloads_content_sha256', table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_index('ix_player_aliases_alias', table_name='player_aliases')
    op.drop_table('player_aliases')
    op.drop_index('ix_normalization_reviews_status', table_name='normalization_reviews')
    op.drop_table('normalization_reviews')
    op.drop_index(op.f('ix_teams_normalized_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('sources')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###

